import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import toast from "react-hot-toast";
import {
  Download,
  Cpu,
  MessageSquare,
  Zap,
  Puzzle,
  Users,
  Award,
} from "lucide-react";

import { candidateAPI, interviewAPI, reportAPI } from "../services/api";

import ScoreCard from "../components/ScoreCard.jsx";
import Loader from "../components/Loader.jsx";

const decisionStyle = {
  Hire: {
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    text: "text-emerald-400",
  },

  Hold: {
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    text: "text-amber-400",
  },

  Reject: {
    bg: "bg-red-500/10",
    border: "border-red-500/30",
    text: "text-red-400",
  },
};

export default function CandidateReport() {
  const [candidate, setCandidate] = useState(null);
  const [interview, setInterview] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadReport = async () => {
      try {
        const cRes = await candidateAPI.getMyProfile();

        const candidateData = cRes.data.data.candidate;

        setCandidate(candidateData);

        const iRes = await interviewAPI.getByCandidate(candidateData._id);

        setInterview(iRes.data.data.interview);
      } catch (err) {
        toast.error(
          err.response?.data?.message || "Unable to load candidate report.",
        );
      } finally {
        setLoading(false);
      }
    };

    loadReport();
  }, []);

  const handleDownloadPDF = async () => {
    try {
      const response = await reportAPI.download(candidate._id);

      const url = window.URL.createObjectURL(new Blob([response.data]));

      const link = document.createElement("a");

      link.href = url;
      link.download = `RecruitIQ_Report_${candidate.fullName}.pdf`;

      document.body.appendChild(link);

      link.click();

      link.remove();

      window.URL.revokeObjectURL(url);
    } catch (err) {
      toast.error(err.response?.data?.message || "Unable to download PDF.");
    }
  };

  if (loading) {
    return <Loader fullScreen label="Loading Candidate Report..." />;
  }

  if (!interview?.evaluation?.decision) {
    return (
      <div className="max-w-2xl mt-50 mx-auto px-6 py-20 text-center ">
        <p className="text-slate-400 text-lg">
          Your final evaluation isn't ready yet.
        </p>

        <p className="text-slate-500 text-sm mt-2">
          Please complete your interview first.
        </p>
      </div>
    );
  }

  const evaluation = interview.evaluation;

  const style = decisionStyle[evaluation.decision] || decisionStyle.Hold;

  return (
    <div className="max-w-6xl mt-10 mx-auto px-6 py-12">
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
      >
        {/* Header */}

        <div className="flex items-center justify-between mb-10">
          <div>
            <h1 className="text-3xl font-bold text-white">
              AI Candidate Report
            </h1>

            <p className="text-slate-400 mt-1">
              Complete interview evaluation generated by RecruitIQ AI
            </p>
          </div>

          <button
            onClick={handleDownloadPDF}
            className="btn-secondary flex items-center gap-2"
          >
            <Download size={16} />
            Download PDF
          </button>
        </div>

        {/* Recommendation */}

        <div
          className={`rounded-2xl border ${style.bg} ${style.border} p-8 mb-10`}
        >
          <div className="flex items-center gap-5">
            <Award size={42} className={style.text} />

            <div>
              <p className="text-sm uppercase tracking-widest text-slate-400">
                Final Recommendation
              </p>

              <h2 className={`text-4xl font-bold mt-1 ${style.text}`}>
                {evaluation.decision}
              </h2>
            </div>
          </div>
        </div>

        {/* Score Cards */}

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mb-10">
          <ScoreCard
            label="Technical"
            score={evaluation.technicalScore}
            icon={Cpu}
            delay={0}
          />

          <ScoreCard
            label="Communication"
            score={evaluation.communicationScore}
            icon={MessageSquare}
            delay={0.05}
          />

          <ScoreCard
            label="Confidence"
            score={evaluation.confidenceScore}
            icon={Zap}
            delay={0.1}
          />

          <ScoreCard
            label="Problem Solving"
            score={evaluation.problemSolvingScore}
            icon={Puzzle}
            delay={0.15}
          />

          <ScoreCard
            label="Behaviour"
            score={evaluation.behaviourScore}
            icon={Users}
            delay={0.2}
          />

          <ScoreCard
            label="Overall Score"
            score={evaluation.overallScore}
            icon={Award}
            delay={0.25}
          />
        </div>

        {/* Summary */}

        <div className="glass-card p-7 mb-8">
          <h3 className="text-lg font-semibold text-white mb-3">
            AI Interview Summary
          </h3>

          <p className="text-slate-400 leading-8">{evaluation.justification}</p>
        </div>

        {/* Strengths & Concerns */}

        <div className="grid md:grid-cols-2 gap-6">
          <div className="glass-card p-7">
            <h3 className="text-lg font-semibold text-emerald-400 mb-4">
              Strengths
            </h3>

            <ul className="space-y-3">
              {(evaluation.strengths || []).map((item, index) => (
                <li key={index} className="flex gap-3 text-slate-300">
                  <span className="text-emerald-400">✔</span>

                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div className="glass-card p-7">
            <h3 className="text-lg font-semibold text-amber-400 mb-4">
              Areas for Improvement
            </h3>

            <ul className="space-y-3">
              {(evaluation.concerns || []).map((item, index) => (
                <li key={index} className="flex gap-3 text-slate-300">
                  <span className="text-amber-400">•</span>

                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
